# Generated by Django 2.2.24 on 2021-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('variant', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
